Name : Jainam Rajput

SAP ID : 60009200022

Div/Batch : K/K1

In [ ]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D

In [ ]:
def split_sequence(sequence,steps):
  X,y = list(), list()
  for start in range(len(sequence)):
    index_end = start+steps
    if index_end>len(sequence)-1:
      break
    sequence_x, sequence_y = sequence[start: index_end],sequence[index_end]
    X.append(sequence_x)
    y.append(sequence_y)
  return array(X), array(y)

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Daily_Electricity_Consumption.csv')

In [ ]:
df.head()

Date  usage  cost
0  2016-10-22   4.52  0.60
1  2016-10-23  23.32  4.36
2  2016-10-24   7.16  1.20
3  2016-10-25   8.68  1.60
4  2016-10-26   5.04  0.84

In [ ]:
import numpy as np
usage = np.array(df['usage'])

In [ ]:
steps = 3
X,y = split_sequence(usage,steps)

print("The input raw sequence on which we will test put CNN model is : ")
print(usage)

print("\n\nThe features (X), lagged values of time series, for our CNN model : ")
print(X)

print("\n\nThe respective observed values (y) of the sequence for training in CNN model:")
print(y)

The input raw sequence on which we will test put CNN model is : 
[ 4.52 23.32  7.16  8.68  5.04  5.32  4.64 10.64  7.44  8.84 11.44 18.2
 14.16  8.28 19.64  6.88  7.28  6.04  9.04 11.24  6.48 10.28 16.4   8.44
  5.64 10.   19.04 17.68 10.36  7.    9.44 16.28 19.2  22.2  13.8  10.4
 15.68 23.08 26.44 24.32 12.52 34.08 16.08 10.36 13.8  11.52 26.52 19.84
 13.04  8.32  0.   19.36 25.96  8.56  8.2  11.08 12.68 33.2  33.68 29.04
 25.32 18.4  18.   24.72 31.96 33.84 20.8  34.32 35.32 16.24 17.76 39.72
 32.28 22.68 15.64 15.44 26.4  26.48 17.76 10.96 19.28 18.04 22.76 19.16
 28.4  37.36 34.88 21.2  20.16 29.8  18.32 21.04 27.92 23.08 23.2  23.04
 24.76 28.52 27.28 20.16 16.2  30.48 18.52 22.52 12.24  7.84 21.76 21.44
 16.04  6.24  9.16  7.24 15.36 24.08 12.92 11.12 13.16  5.52 10.64 21.84
  8.68 16.84  7.72 22.76 29.68 25.92 24.52 26.   20.52 17.84 12.84 18.04
 24.52 16.28 24.28 22.36 14.92 17.12  6.08  5.24  5.24  8.36  7.4   6.92
  7.2   8.36  5.8   7.24  8.84  5.36  5.2   5.76  4.8  10.88 

In [ ]:
features = 1
X = X.reshape((X.shape[0],X.shape[1],features))

print("After Shaping the shape of input X is : ")
print(X.shape)

print("The final form of input feature matrix X : ")
print(X)

After Shaping the shape of input X is : 
(730, 3, 1)
The final form of input feature matrix X : 
[[[ 4.52]
  [23.32]
  [ 7.16]]

 [[23.32]
  [ 7.16]
  [ 8.68]]

 [[ 7.16]
  [ 8.68]
  [ 5.04]]

 ...

 [[ 7.76]
  [ 8.  ]
  [ 1.12]]

 [[ 8.  ]
  [ 1.12]
  [ 0.64]]

 [[ 1.12]
  [ 0.64]
  [ 1.2 ]]]


## Model Building

In [ ]:
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(steps,features)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(100, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam',loss=['mse'],metrics=['mae','mape'])

In [ ]:
model.fit(X,y,epochs=1000, verbose=True)

Epoch 1/1000
23/23 [==============================] - 1s 4ms/step - loss: 131.7714 - mae: 9.1365 - mape: 8695864.0000
Epoch 2/1000
23/23 [==============================] - 0s 5ms/step - loss: 34.5502 - mae: 4.2335 - mape: 26778944.0000
Epoch 3/1000
23/23 [==============================] - 0s 5ms/step - loss: 33.2474 - mae: 4.1238 - mape: 23605840.0000
Epoch 4/1000
23/23 [==============================] - 0s 4ms/step - loss: 33.0300 - mae: 4.1049 - mape: 24426746.0000
Epoch 5/1000
23/23 [==============================] - 0s 4ms/step - loss: 32.3809 - mae: 4.0473 - mape: 23436304.0000
Epoch 6/1000
23/23 [==============================] - 0s 6ms/step - loss: 32.0302 - mae: 4.0266 - mape: 24110700.0000
Epoch 7/1000
23/23 [==============================] - 0s 4ms/step - loss: 31.7963 - mae: 4.0129 - mape: 24120524.0000
Epoch 8/1000
23/23 [==============================] - 0s 5ms/step - loss: 31.5393 - mae: 3.9880 - mape: 23390764.0000
Epoch 9/1000
23/23 [==============================] - 0s

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 2, 64)             192       
                                                                 
 max_pooling1d (MaxPooling1D  (None, 1, 64)            0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 64)                0         
                                                                 
 dense (Dense)               (None, 100)               6500      
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 6,793
Trainable params: 6,793
Non-trainable params: 0
______________________________________________________

In [ ]:
x_input = array([6,5,8])
x_input = x_input.reshape((1,steps,features))
y_pred = model.predict(x_input,verbose=0)
print("The next predicted value for the sequence is ")
print(y_pred)

The next predicted value for the sequence is 
[[8.181513]]
